### ISSUE TITLE
demoForceImitation won't work

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/icub-basic-demos#10]
Hello
we would like to execute demoForceImitation but we are encountering problems.
For example, the ports used do not exist:

/armSkinDriftComp/skin_events:o

cannot be found when we launch the skinManager with our robot. We also noticed that the module skinDriftCompensation is not existing anymore.

How can this be fixed? 
Thanks in advance

ps: we have iCubNancy01

**Comment by pattacini** [comment]
Hi @serena-ivaldi,

I've fixed the `autoconnect` option via 58d66d1ec13a770ec9903514dd005f70095587ef.

However, [this xml app](https://github.com/robotology/icub-basic-demos/blob/master/demoForceImitation/app/scripts/demoForceImitation.xml.template) - shipped within the repo - was already correct.
