### ISSUE TITLE
Cannot launch demoYoga

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/icub-basic-demos#12]
Hello
I am trying to launch the demoYoga but it won't start from a file other than yoga.ini

This works:
``demoYoga --robot icubSim ``
using yoga.ini

However, I cannot make it work from any file.
I tried:
``demoYoga --robot icubSim --from two-hands.ini``
``demoYoga --robot icubSim --config two-hands.ini``
``demoYoga --robot icubSim --file two-hands.ini``

None of the three work... How should I launch it?

ps: by the way, you should add the prefix of the yoga folder to the ini file of yoga.ini

**Comment by pattacini** [comment]
Hi @serena-ivaldi 

The option [**`--positions`**][1]`file-name` should do the job.
Consider that `demoYoga` is very old, thus does not comply with our standards, is no longer used and there's no chance we're going to upgrade it 😉 

[1]: https://github.com/robotology/icub-basic-demos/blob/master/demoYoga/src/main.cpp#L508

**Comment by serena-ivaldi** [comment]
What do you use to make simple demos like the yoga?

**Comment by pattacini** [comment]
Hi @serena-ivaldi 

- For reproducing trajectories at the joints level we use [`ctpService`][1].
- For controlling the movements of the arm in the Cartesian space, we use [`cartesianInterfaceControl`][2].
- For controlling the gaze, obviously, the [`iKinGazeCtrl`][3] module.

All the above modules can be managed through bash scripts as done for example in [`funny-things`][4] repository.

[1]: http://wiki.icub.org/iCub/main/dox/html/group__ctpService.html
[2]: http://wiki.icub.org/iCub/main/dox/html/group__cartesianInterfaceControl.html
[3]: http://wiki.icub.org/iCub/main/dox/html/group__iKinGazeCtrl.html
[4]: https://github.com/robotology/funny-things/tree/master/app/scripts/shells
