### ISSUE TITLE
Compilation Error - missing function

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-basic-demos#13]
Hi All, 

I am working on the **devel** branch (up to date), while trying to compile icub-basic-demos, I've the following compilation error:

```
.../src/icub-basic-demos/demoForceImitation/src/main.cpp:192:41: error: no member named
      'setReference' in 'yarp::dev::IPidControl'
                robot->ipid[RIGHT_ARM]->setReference(i,encoders_master[i]);
                ~~~~~~~~~~~~~~~~~~~~~~  ^
.../src/icub-basic-demos/demoForceImitation/src/main.cpp:201:40: error: no member named
      'setReference' in 'yarp::dev::IPidControl'
                robot->ipid[LEFT_ARM]->setReference(i,encoders_master[i]);
                ~~~~~~~~~~~~~~~~~~~~~  ^
2 errors generated.
make[2]: *** [demoForceImitation/CMakeFiles/demoForceImitation.dir/src/main.cpp.o] Error 1
make[1]: *** [demoForceImitation/CMakeFiles/demoForceImitation.dir/all] Error 2
make: *** [all] Error 2
```

Cheers, 
Alex.

**Comment by pattacini** [comment]
Hi @amaroyo thanks for reporting.
We're doing a major overhaul of yarp in view of version 3.0, hence many breakages may occur in `devel`.
The suggestion is, therefore, to stick to `master`.

**Comment by amaroyo** [comment]
It's not a problem! I just wanted to let you know :) 

We're using the iCubGenova03 with the devel branch, that's why I am not in master.

**Comment by pattacini** [comment]
Yes indeed, thanks!
Let's keep this open until it will be fixed - which might occur quite soon by the way.
Mine was more a suggestion for possible future breakages you might discover on `devel`.
