### ISSUE TITLE
icub-basic-demos : compile fails

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-basic-demos#16]
I'm testing the robot SN039; all repo updated today, icub-basic-demos fails to compile.
Attached the failure log.

@pattacini  @randaz81 @valegagge 
[log.txt](https://github.com/robotology/icub-basic-demos/files/3402306/log.txt)

**Comment by pattacini** [comment]
Fixed in https://github.com/robotology/icub-basic-demos/commit/bde3d96cbcd20830385522fccd776aff1a935839.

Thanks @davidetome for reporting.
