### ISSUE TITLE
RedBallDemo Crash while tracking red ball

### ISSUE THREAD

**Issue by 0707yiliu** [robotology/icub-basic-demos#25]
When we were doing the red ball tracking experiment, icub sometimes wrote the red ball on its head, which lead the process broken down. In this pose, we cannot use robotmotorgui control the robotic motor.

I suspect it is  the parameter configuration of tracker.

Here is my configuration
####################################
#configuration file for PF3DTracker#
####################################

#############
#module name#
#############
name                        /pf3dTracker

#############################
#parameters of the algorithm#
#############################
nParticles                  600
#nParticles                 number of particles used
accelStDev                  30
#accelStDev                 50 30 15
#accelStDev                 standard deviation of the acceleration noise
insideOutsideDiffWeight     1.5
#insideOutsideDiffWeight    inside-outside difference weight for the likelihood function
colorTransfPolicy           1
#colorTransfPolicy          [0=transform the whole image | 1=only transform the pixels you need]

#########################
#port names and function#
#########################
inputVideoPort              /pf3dTracker/video:i 
#inputVideoPort             receives images from the grabber or the rectifying program.
outputVideoPort             /pf3dTracker/video:o
#outputVideoPort            produces images in which the contour of the estimated ball is highlighted
outputDataPort              /pf3dTracker/data:o
#outputDataPort             produces a stream of data in the format: X, Y, Z, likelihood, U, V, seeing_object
outputParticlePort          /pf3dTracker/particles:o
#outputParticlePort         produces data for the plotter. it is usually not active for performance reasons.
inputParticlePort           /pf3dTracker/particles:i   
#inputParticlePort          recives hypotheses on the ball position from pf3dBottomup.
outputAttentionPort         /pf3dTracker/attention:o
#outputAttentionPort        produces data for the attention system, in terms of a peak of saliency.

#################################
#projection model and parameters#
#################################
#projectionModel [perspective|equidistance|unified]
projectionModel             perspective

cameraContext  cameraCalibration
cameraFile     icubEyes1.ini
cameraGroup    CAMERA_CALIBRATION_LEFT

#######################
#tracked object models#
#######################
#trackedObjectType [sphere|parallelogram]
trackedObjectType           sphere
#trackedObjectColorTemplate  models/red_ball_iit.bmp
trackedObjectColorTemplate  models/red_smiley_2009_07_02.bmp
#trackedObjectShapeTemplate  models/initial_ball_points_36mm_20percent.csv
trackedObjectShapeTemplate  models/shape_model_26_30.csv

motionModelMatrix           models/motion_model_matrix.csv
trackedObjectTemp           current_histogram.csv

#######################
#initialization method#
#######################
#initialization method [search|3dEstimate|2dEstimate]
initializationMethod        3dEstimate
initialX                       0
initialY                       0
initialZ                       0.5

####################
#visualization mode#
####################
#circleVisualizationMode	[0=inner and outer cirlce | 1=one circle with the correct radious] default 0. only applies to the sphere.
circleVisualizationMode	1

#########################
#attention-related stuff#
#########################
#the tracker produces a value of likelihood at each time step. this value can be used to infer if the object it is tracking is the correct one. this is not a very robust way of doing so.
#if likelihood>this value, then probably I'm tracking the object. 20Millions is good, 12Millions is the likelihood of Jonas Hornsteins's PC screen (false positive).
#20Millions is a good threshold level when you have the right color model. 5M.
likelihoodThreshold         0.0004
attentionOutputMax          250
attentionOutputDecrease     0.99

##########################
#image saving preferences#
##########################
#save images with OpenCV?
saveImagesWithOpencv        false
#always use the trailing slash here.
saveImagesWithOpencvDir     ./graphical_results/

**Comment by pattacini** [comment]
What do you mean by "_icub sometimes writes the red ball on its head_"?

I guess you meant that the ball was recognized too close to the camera and the hand was brought there? Did I get it right?

Which module crashed in particular?

**Comment by 0707yiliu** [comment]
That's right, the red ball will be displayed on the head of the iCub on icubGUI. 

And then, icub will get stuck in that position and can only be recovered by pressing the emergency stop button and restarting the robotinterface module.

**Comment by pattacini** [comment]
Following the recommendations in https://github.com/robotology/icub-basic-demos/issues/24#issuecomment-665017818, you shouldn't enable the use of the arms until the ball gets correctly recognized at the right distance in the whole robot's workspace.

Instead of pressing the fault-button, when the robot seems to be stuck at a given position, try out closing the application. Unless one particular component has crashed, this should work out.

**Comment by 0707yiliu** [comment]
Hi @pattacini 
Your method is right. I increased the traj_time yestoday.

But the motors' speed in the part of head don't decrease. Icub will move its crazy head.

I added a low-pass-filter in Tracker because the identified fluctuation is in centimeters level. If you suddenly approach icub, its likelihood increases too much. That's probably why it thought the ball was on its head. It may also be related to environment lighting factors.

**Comment by pattacini** [comment]
Those parameters only account for the speed of the arms not of the head.

What are the command-line options of `iKinGazeCtrl` when launching the demo? Likely, it gets launched as:
```xml
<name>iKinGazeCtrl</name>
<parameters>--from iKinGazeCtrl.ini</parameters>
```

Therefore, do
```sh
$ yarp resource --context iKinGazeCtrl --from iKinGazeCtrl.ini
```
in order to locate the conf file that is used at startup.

If the location of `iKinGazeCtrl.ini` (or any other conf file) on the machine where it runs is NOT in `~/.local/share/yarp/...` then do:
```sh
$ yarp-config context --import iKinGazeCtrl
```
so that those conf files are copied out in the `.local` path.

Once done, run again:
```sh
$ yarp resource --context iKinGazeCtrl --from iKinGazeCtrl.ini
```
and, finally, customize the file located this way.

The documentation of `iKinGazeCtrl` is available online at https://robotology.github.io/robotology-documentation/doc/html/group__iKinGazeCtrl.html.

In particular, take a look at:
- `--trajectory_time::neck <val_1>`
- `--trajectory_time::eyes <val_2>`

Default values for <val_1> and <val_2> are `0.75 s` and `0.25 s`, respectively. Try out to increase the neck time response first. If not present in the conf file yet, you ought to add the following lines:

```ini
[trajectory_time]
neck new_val_1
```

Also, you could disable the IMU:
```ini
[imu]
mode off
```

Alternatively, you may want to modify the XML:
```xml
<name>iKinGazeCtrl</name>
<parameters>--from iKinGazeCtrl.ini --trajectory_time::neck <new_val_1> --imu::mode off</parameters>
```

**Comment by 0707yiliu** [comment]
Actually, I think the head movement factor is very small. But I will modify the speed of the head motor.

After the last time icub collapsed, which left eye may have a focal length problem. I adjusted the parameters that can be adjusted by the camera to no avail. 
Is there something wrong with the mechanical part of the camera???

**Comment by pattacini** [comment]
>Actually, I think the head movement factor is very small. But I will modify the speed of the head motor.

It's not that small as the head can move quite rapidly given its low inertia. We often use it that way and even lower.
Of course, if the gaze receives incorrect targets, the head will start moving weirdly in the attempt to track them.

>Is there something wrong with the mechanical part of the camera???

As usual, please open up a ticket on https://github.com/robotology/icub-tech-support for this kind of matter.
