### ISSUE TITLE
DemoYoga without legs

### ISSUE THREAD

**Issue by violadelbono** [robotology/icub-basic-demos#27]
Hi @pattacini 

With the new robot S/N:043 we cannot launch the demoYoga without the legs. We modified the file `yoga.ini` removing both the legs files .ini but the software is still complaining and cannot find the related ports.

Do you know if there is another file(s) that we need to modify or a special command parameter to launch this demo without the legs?

cc @julijenv

**Comment by pattacini** [comment]
@violadelbono I've just transferred the issue here in `icub-basic-demos` as the yoga belongs actually to this repo.
I'll have a look into this although I can already tell you that this component is the oldest we have as well as the less maintained.

**Comment by violadelbono** [comment]
Thank you!

**Comment by pattacini** [comment]
As I was afraid of, the author did not foresee the possibility to disable limbs, hence your only chance is to proceed with a local hack.

I would then suggest that you replace LIMBS w/ `4` here:
https://github.com/robotology/icub-basic-demos/blob/d00f0702a12f3ec4a7989f04a737e38b9ad6f4fb/demoYoga/src/main.cpp#L147

Finally, comment out the following code lines:
https://github.com/robotology/icub-basic-demos/blob/d00f0702a12f3ec4a7989f04a737e38b9ad6f4fb/demoYoga/src/main.cpp#L546-L554

Once done, rebuild the project 🌀 
Hopefully, it won't seg-fault! 🤞🏻

**Comment by pattacini** [comment]
@Nicogene I would really declare `demoYoga` deprecated! It's being used only for tests, after all.

We could replace this component with a bunch of trajectory files recorded with `yarpdatadumper` to then use `wholeBodyPlayer` to selectively run the sequences for the desired limbs.

How do you see that? 👍🏻 👎🏻

**Comment by pattacini** [comment]
Any news on this? Did it work?

**Comment by violadelbono** [comment]
@pattacini I followed your instructions but I still get the same error:

```
[ERROR]Problem connecting to /icub/right_leg/rpc:i, is the remote device available?
[ERROR]Problem connecting to /icub/right_leg/command:i, is the remote device available?
[ERROR]Problem connecting to /icub/right_leg/stateExt:o, is the remote device available?
yarpdev: ***ERROR*** driver <remote_controlboard> was found but could not open
[ERROR]Error opening RIGHTLEG
[ERROR]Error creating devices, check parameters

```

I find it weird that it is complaining only about the right leg now.
I have the feeling that the problem is here:

```
enum Index
{
    RIGHTARM=0,
    LEFTARM=1,
    HEAD=2,
    TORSO=3,
    RIGHTLEG=4,
    LEFTLEG=5,
    LIMBS=4};
```
Should I get rid also of the 2 legs variables?

**Comment by pattacini** [comment]
Then, I need to investigate!
Stay tuned.

**Comment by pattacini** [comment]
Quick update on this @violadelbono.
Although we decided not to go for this adaption, @Nicogene is gonna provide you with a local hack (probably a zip) for letting the yoga run with the upper body only.

**Comment by Nicogene** [comment]
> @Nicogene I would really declare demoYoga deprecated! It's being used only for tests, after all.

>We could replace this component with a bunch of trajectory files recorded with yarpdatadumper to then use wholeBodyPlayer to selectively run the sequences for the desired limbs.

Seems a good idea it fits very well this use case!
But first we have to check that `wholeBodyPlayer` works well also on the real robot, unfortunately I didn't find the time yet 😓

**Comment by Nicogene** [comment]
At the end I made it configurable(see https://github.com/robotology/icub-basic-demos/pull/28) since it had the same cost and it may be useful to not use legs.

@violadelbono could you please checkout in the branch and  try it on the sn 43? On the simulator it works

**Comment by pattacini** [comment]
I've merged it straight away!
@violadelbono you could pull `master` directly!

**Comment by pattacini** [comment]
@violadelbono you should be running the executable specifying the command-line option `--no_legs`.

**Comment by violadelbono** [comment]
@pattacini @Nicogene 

I just tested the new DemoYoga and it is correctly working 🎉 thanks guys
