### ISSUE TITLE
A problem with the Yoga demo

### ISSUE THREAD

**Issue by SSSSamZhu** [robotology/icub-basic-demos#37]
I now have a problem with the Yoga demo, as shown in the picture
![Screenshot from 2022-04-25 10-22-06](https://user-images.githubusercontent.com/100264795/165011076-f0fccdeb-55c0-4296-9401-18cdacfff343.png)
![Screenshot from 2022-04-25 10-28-56](https://user-images.githubusercontent.com/100264795/165011171-725e6866-b806-4df9-86c1-89c78ef75c65.png)

From iCub Shenzhen01

**Comment by pattacini** [comment]
Hi @SSSSamZhu 

Did you check the [documentation](https://github.com/robotology/icub-basic-demos#documentation)?

If you take a look at the [`demoYoga` documentation][doc] (very slim and essential actually), you'll find out that the binary needs 2 input parameters:
- `--robot robotname` that serves to specify the name of the robot.
- `--positions filename` specifying the file that contains the trajectories.

Therefore, something like the following should work:
```console
demoYoga --robot icub --positions yoga.ini
```

Hope this helps.

---

<sub>Remember to make sure that `yarpserver` is running and can be reached by all the machines connected to your cluster, robot included, and that the yarp namespace is correctly set up.</sub>

[doc]: http://robotology.github.io/icub-basic-demos/doxygen/doc/html/group__src__demoYoga.html

**Comment by SSSSamZhu** [comment]
Thanks for your help, I have solved this problem and I will close this issue.
Thanks!
