### ISSUE TITLE
CI Workflow (CONDA) fails

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-basic-demos#40]
See https://github.com/robotology/icub-basic-demos/actions/workflows/conda-ci.yml.

**Comment by traversaro** [comment]
The issue is that on windows-latest there is no vs2019 and conflicts of the internal conda with setup-miniconda. You can check in the idynfor repo or wb-toolbox for a working template.

**Comment by pattacini** [comment]
> [!note]
I've disabled the CI for the time being.

**Comment by Nicogene** [comment]
CI now is happy:

- https://github.com/robotology/icub-basic-demos/actions/runs/5963577822
