### ISSUE TITLE
demoRedBall doesn't set joints in position when it ends

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-basic-demos#5]
When I stop the demo, I see the joints (involved in the demo) in mixed mode or position direct by motorgui.

**Comment by pattacini** [comment]
It doesn't have to :)

**Comment by valegagge** [comment]
why? is the policy changed?

**Comment by pattacini** [comment]
That's actually the new policy: whoever wants to control the robot needs to set the control mode accordingly.
