### ISSUE TITLE
demoRedBall traj_time value inconsistency

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-basic-demos#6]
Hi @pattacini, just wanted to report that the parameter `traj_time` has the value 2.0 in the doxygen & code, but a different value 1.5 in the ini files.

**Comment by pattacini** [comment]
Hi @gsaponaro 

Values in the doxygen doc are definitely not representative.

**Comment by gsaponaro** [comment]
Sure. I mainly noticed the difference between code (where `trajTime=bGeneral.check("traj_time",Value(2.0)...`) and ini (where `traj_time 1.5`), in case you deemed worthy making them consistent. Doxygen was mentioned just for completeness, but I agree that one is not really important.

**Comment by pattacini** [comment]
I think it's very likely that other parameters in the config files for this demo and other demos too don't match the hard-coded default values, so ... :smirk:

**Comment by pattacini** [comment]
Then, I don't really think it's a real inconsistency: it's just a matter of different levels of "_default values_".

**Comment by gsaponaro** [comment]
OK. :)
